"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


APP = ['gui/system_tray.py']
DATA_FILES = []
PKGS = ['netifaces', 'pysqlcipher']
OPTIONS = {
    'argv_emulation': True,
    'plist': {'LSUIElement': True,
              'NSHumanReadableCopyright': 'Copyright 2016 Brandon Ragsdale',
              'CFBundleIdentifier': 'org.pythonmac.unspecified.KeepInChecker',
              'CFBundleName': 'KeepInChecker',
              'CFBundleDisplayName': 'KeepInChecker',
              'CFBundleShortVersionString': '1.0'},
    'iconfile': 'gui/images/chevron-up.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
